from quantbench.portfolio.optimize import PORTFOLIO_METHODS
from quantbench.config import PORTFOLIO_DEFAULT_METHOD

FETCH_OHLCV_PARAMS = {
    "type": "object",
    "properties": {
        "symbol": {"type": "string", "description": "e.g. BTC/USDT for crypto, AAPL/MSFT/SPY for US equities"},
        "timeframe": {"type": "string", "description": "e.g. 4h for crypto, 1d for equities"},
        "start": {"type": "string", "description": "YYYY-MM-DD"},
        "end": {"type": "string", "description": "YYYY-MM-DD"},
    },
    "required": ["symbol", "timeframe", "start", "end"],
}

SIGNAL_FILE_HEADER = '''"""QuantBench Phase 0 signal - generated by the Coordinator agent.

Runnable standalone: `python signal.py <data.parquet> [--output out.csv]`
"""
import numpy as np
import pandas as pd


'''

SIGNAL_FILE_HARNESS = '''

if __name__ == "__main__":
    import argparse
    import os
    import sys
    from contextlib import contextmanager

    sys.dont_write_bytecode = True
    parser = argparse.ArgumentParser()
    parser.add_argument("data_path")
    parser.add_argument("--output")
    args = parser.parse_args()

    @contextmanager
    def _suppress_native_stderr():
        stderr_fd = 2
        saved_fd = os.dup(stderr_fd)
        try:
            with open(os.devnull, "w") as devnull:
                os.dup2(devnull.fileno(), stderr_fd)
                yield
        finally:
            os.dup2(saved_fd, stderr_fd)
            os.close(saved_fd)

    with _suppress_native_stderr():
        _df = pd.read_parquet(args.data_path)

    if "symbol" in _df.columns:
        # Multi-symbol panel (Phase 1 cross-sectional runs). compute() must be
        # applied per symbol, in the exact same shape run_cross_sectional_backtest
        # uses internally - never across the mixed long table directly, or the
        # reproduced numbers will silently diverge from the real backtest.
        _frames = []
        for _symbol, _symbol_df in _df.groupby("symbol", sort=False):
            _symbol_df = _symbol_df.sort_values("timestamp").reset_index(drop=True)
            _out_symbol = _symbol_df[["timestamp"]].copy()
            _out_symbol["symbol"] = _symbol
            _out_symbol["signal"] = compute(_symbol_df)
            _frames.append(_out_symbol)
        _out = pd.concat(_frames, ignore_index=True).sort_values(["timestamp", "symbol"])
    else:
        _out = _df[["timestamp"]].copy()
        _out["signal"] = compute(_df)

    _csv = _out.to_csv(index=False)
    if args.output:
        with open(args.output, "w", encoding="utf-8") as handle:
            handle.write(_csv)
    else:
        print(_csv)
'''

RUN_SIGNAL_BACKTEST_PARAMS = {
    "type": "object",
    "properties": {
        "code": {
            "type": "string",
            "description": (
                "Python source defining `def compute(df: pd.DataFrame) -> pd.Series`. "
                "Only `pd` and `np` are available, no imports. Must be causal: only use "
                "rows up to and including the current index, never future rows."
            ),
        },
        "cost_bps": {
            "type": "number",
            "description": "Round-trip trading cost in basis points. Default 5.",
        },
        "execution": {
            "type": "object",
            "description": "Execution assumption; fill_price may be close_t, open_t+1, or close_t+1. Default close_t.",
            "properties": {
                "signal_time": {"type": "string"},
                "fill_price": {"type": "string"},
            },
        },
    },
    "required": ["code"],
}

BUILD_UNIVERSE_PARAMS = {
    "type": "object",
    "properties": {
        "universe_name": {
            "type": "string",
            "description": "Universe name, e.g. sp500 or top_usdt_perpetual for crypto perpetual swaps.",
        },
        "as_of_date": {"type": "string", "description": "YYYY-MM-DD date for the universe definition."},
        "point_in_time": {
            "type": "boolean",
            "description": "Use point-in-time membership when supported. For sp500, also pass start and end.",
        },
        "start": {"type": "string", "description": "YYYY-MM-DD backtest start, required when point_in_time is true."},
        "end": {"type": "string", "description": "YYYY-MM-DD backtest end, required when point_in_time is true."},
        "limit": {
            "type": "integer",
            "description": (
                "Optional: truncate to the first N tickers (alphabetically) instead of the "
                "full ~500. Use this whenever the user asks for a quick/small/cheap test - "
                "fetching all 500 symbols sequentially is slow and not needed to sanity-check "
                "a factor idea. The universe is clearly marked as a non-representative sample."
            ),
        },
    },
    "required": ["universe_name", "as_of_date"],
}

RUN_CROSS_SECTIONAL_BACKTEST_PARAMS = {
    "type": "object",
    "properties": {
        "code": {
            "type": "string",
            "description": (
                "Python source defining `def compute(df: pd.DataFrame) -> pd.Series`. "
                "The function is called once per symbol and must be causal."
            ),
        },
        "start": {"type": "string", "description": "YYYY-MM-DD"},
        "end": {"type": "string", "description": "YYYY-MM-DD"},
        "timeframe": {"type": "string", "description": "Use 1d for US equities."},
        "n_groups": {"type": "integer", "description": "Number of factor groups, default 10."},
        "cost_bps": {"type": "number", "description": "Round-trip trading cost in basis points. Default 5."},
        "execution": {
            "type": "object",
            "description": "Execution assumption; fill_price may be close_t, open_t+1, or close_t+1. Default close_t.",
            "properties": {
                "signal_time": {"type": "string"},
                "fill_price": {"type": "string"},
            },
        },
        "liquidity_cost": {
            "type": "object",
            "description": "Optional liquidity-aware cost/capacity model. Disabled unless enabled=true.",
            "properties": {
                "enabled": {"type": "boolean"},
                "aum_usd": {"type": "number"},
                "participation_cap": {"type": "number"},
            },
        },
        "borrow_cost": {
            "type": "object",
            "description": "Optional assumed borrow-cost model for short legs. Disabled unless enabled=true.",
            "properties": {
                "enabled": {"type": "boolean"},
            },
        },
        "neutralize": {
            "type": "array",
            "description": "Optional cross-sectional neutralization dimensions: beta, size, sector. Beta uses a rolling regression against the equal-weight universe return; size uses a dollar-volume proxy.",
            "items": {"type": "string"},
        },
    },
    "required": ["code", "start", "end"],
}

SCREEN_FACTORS_PARAMS = {
    "type": "object",
    "properties": {
        "candidates": {
            "type": "array",
            "description": "Candidate factor list, each item containing name and causal compute() code.",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "code": {"type": "string"},
                },
                "required": ["name", "code"],
            },
        },
        "start": {"type": "string", "description": "YYYY-MM-DD"},
        "end": {"type": "string", "description": "YYYY-MM-DD"},
        "timeframe": {"type": "string", "description": "Use 1d for US equities."},
        "n_groups": {"type": "integer", "description": "Number of factor groups, default 10."},
        "cost_bps": {"type": "number", "description": "Round-trip trading cost in basis points. Default 5."},
        "execution": {
            "type": "object",
            "description": "Execution assumption shared by all candidates. Default close_t.",
            "properties": {
                "signal_time": {"type": "string"},
                "fill_price": {"type": "string"},
            },
        },
        "liquidity_cost": {
            "type": "object",
            "description": "Optional liquidity-aware cost/capacity model shared by all candidates. Disabled unless enabled=true.",
            "properties": {
                "enabled": {"type": "boolean"},
                "aum_usd": {"type": "number"},
                "participation_cap": {"type": "number"},
            },
        },
        "borrow_cost": {
            "type": "object",
            "description": "Optional assumed borrow-cost model for short legs. Disabled unless enabled=true.",
            "properties": {
                "enabled": {"type": "boolean"},
            },
        },
        "neutralize": {
            "type": "array",
            "description": "Optional cross-sectional neutralization dimensions: beta, size, sector. Beta uses a rolling regression against the equal-weight universe return; size uses a dollar-volume proxy.",
            "items": {"type": "string"},
        },
    },
    "required": ["candidates", "start", "end"],
}


OPTIMIZE_PORTFOLIO_PARAMS = {
    "type": "object",
    "properties": {
        "run_ids": {
            "type": "array",
            "description": (
                "run_id list of existing completed runs to combine (e.g. from a prior screen_factors call, "
                "or named directly by the user). Each must have its own backtest_result.json return series, "
                "and all must share the same asset class."
            ),
            "items": {"type": "string"},
        },
        "method": {
            "type": "string",
            "description": (
                f"One of {PORTFOLIO_METHODS}. Optional - defaults to '{PORTFOLIO_DEFAULT_METHOD}' (risk parity, "
                "which never estimates expected returns and is the recommended default). 'max_sharpe' is computed "
                "and reported for every call regardless of which method is selected, purely as a comparison point - "
                "it is the most overfitting-prone method here and should not be recommended to the user as the choice."
            ),
        },
        "cost_bps": {"type": "number", "description": "Round-trip rebalancing cost in basis points. Default 5."},
        "split": {
            "type": "number",
            "description": "Fraction of the overlapping history used to fit weights in-sample; the remainder is held out. Default 0.7.",
        },
        "max_weight": {"type": "number", "description": "Upper bound on any single factor's weight. Default 0.6."},
    },
    "required": ["run_ids"],
}


CHECK_RUN_DECAY_PARAMS = {
    "type": "object",
    "properties": {
        "run_id": {
            "type": "string",
            "description": (
                "run_id of an existing STRONG/PROMISING run (single-symbol, cross-sectional, or portfolio) to "
                "check for live decay: freshly re-fetches recent market data, re-runs the run's own factor code "
                "on it, and compares the resulting Sharpe to the run's original backtest Sharpe. Deterministic - "
                "does not create a new run or call the Critic; only reports facts about the existing run."
            ),
        },
    },
    "required": ["run_id"],
}


CRYPTO_PERPETUAL_FUNDING_WARNING = (
    "Crypto perpetual backtests do not model funding rate carry cost. Long-short "
    "positions held across funding intervals may have systematically biased PnL "
    "that this backtest does not capture."
)
